# Generated by Django 2.2.1 on 2019-07-02 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booktest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='pad_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
