# Generated by Django 2.2.1 on 2019-07-17 01:35

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_news_newsdetail_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdetail',
            name='content',
            field=DjangoUeditor.models.UEditorField(),
        ),
    ]
