# Generated by Django 2.2.1 on 2019-07-03 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HerosInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('hp', models.CharField(max_length=20)),
                ('mp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('hurt', models.CharField(max_length=20)),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.HerosInfo')),
            ],
        ),
    ]
