# Generated by Django 2.2.1 on 2019-07-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], default=True, max_length=5),
        ),
        migrations.AddField(
            model_name='herosinfo',
            name='type',
            field=models.CharField(choices=[('close', '近战'), ('near', '远战')], default=True, max_length=5),
        ),
    ]
