# Generated by Django 2.2.1 on 2019-07-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametest', '0002_auto_20190704_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], default='男', max_length=5),
        ),
        migrations.AlterField(
            model_name='herosinfo',
            name='type',
            field=models.CharField(choices=[('close', '近战'), ('near', '远战')], default='近战', max_length=5),
        ),
    ]
