# Generated by Django 2.2.1 on 2019-07-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gametest', '0003_auto_20190704_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosinfo',
            name='gender',
            field=models.CharField(choices=[('man', '男'), ('woman', '女')], default='man', max_length=5),
        ),
    ]
