# Generated by Django 2.2.1 on 2019-07-16 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('grade', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold', models.IntegerField(default=0)),
                ('bluebrick', models.IntegerField(default=0)),
                ('powderbrick', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=50)),
                ('lskill', models.CharField(max_length=50)),
                ('pskill', models.CharField(max_length=50)),
                ('skillcontent', models.TextField()),
                ('type', models.CharField(max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grade', models.IntegerField(default=0)),
                ('phero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Warsprit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('grouptype', models.CharField(max_length=20)),
                ('wshero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Hero')),
            ],
        ),
        migrations.CreateModel(
            name='Petdetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField(default=10)),
                ('mp', models.IntegerField(default=10)),
                ('quality', models.CharField(max_length=10)),
                ('ptype', models.CharField(max_length=10)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Othergoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(max_length=20)),
                ('gtype', models.CharField(max_length=10)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Goods')),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='ghero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Hero'),
        ),
        migrations.CreateModel(
            name='Attck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma', models.CharField(max_length=10)),
                ('md', models.CharField(max_length=10)),
                ('wa', models.CharField(max_length=10)),
                ('wd', models.CharField(max_length=10)),
                ('warsprit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Warsprit')),
            ],
        ),
        migrations.CreateModel(
            name='Arms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(max_length=10)),
                ('chest', models.CharField(max_length=10)),
                ('leg', models.CharField(max_length=10)),
                ('badge', models.CharField(max_length=10)),
                ('feet', models.CharField(max_length=10)),
                ('ahero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gametest.Hero')),
            ],
        ),
    ]
